### ISSUE TITLE
should.have.been.called.once Does Not Work as Expected

### ISSUE THREAD

**Issue by pahund** [domenic/sinon-chai#71]
I have a test that I expect to fail, because I have not yet implemented the functionality.
A spy should only have been called once.
According to the [Sinon Spy API documentation](http://sinonjs.org/docs/#spies-api), `spy.calledOnce` should be `true` if the spy was called exactly once.
If I use sinon-chai's `should.have.been.called.once`, it returns true for my spy although the spy was, in fact called twice.
For clarification, here's a screenshot of my test code:
<img width="1146" alt="sinon-chai-bug" src="https://cloud.githubusercontent.com/assets/1639313/10689686/6597c316-797d-11e5-8685-8b529ba0caba.png">

**Comment by djbeaumont** [comment]
We've noticed what looks to be a related issue: `expect(undefined).to.have.been.called;` passes unexpectedly, but the issue is resolved when using dirty-chai.

Reproduced here: https://github.com/djbeaumont/chai-undefined

**Comment by domenic** [comment]
@pahund There is no `.called.once` asserter; use `.calledOnce`.

@djbeaumont in https://github.com/domenic/sinon-chai/commit/4397aa15f5a6c01539b9f1f4b9798a6d5b3e31f0 I added a test showing that you get a TypeError. Your repro repository is not valid since it installs dirty-chai, which overrides Sinon-Chai's `.called` property with a `.called()` method. So of course when dirty-chai is installed, `.called` will not work, since it is not a property anymore.
